---
title: "Data_Prep"
author: "Pete"
date: "2024-03-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

``` {r Load libraries}
library(readxl)
library(readr)
library(plyr)
library(dplyr)
library(lubridate)
library(data.table)  
library(tidyverse)
library(lme4)

library('RHRV') #Heart Rate Analysis
library(semiArtificial)

library(Metrics)

```

``` {r Config}
my_options <- options(digits.secs = 3) #for time in millisecond

# Sim_freq <- 1000
HR_freq <- 64
EDA_freq <- 4
eye_freq <- 125

target_sampling_rate <- 32

pre_takeover_sec <- 7 #before (alert) trigger launched
post_takeover_sec <- 8 #after (alert) trigger launched

extractBaselineData <- FALSE
trigger_ID_config <- data.frame(design = c("X","Y"),
                                trigger_ID = c(3,2))
```

``` {r Helper Functions}

replaceColNamePattern <- function(df, pattern, replace){ 
  names(df) <- gsub(pattern, replace, names(df))
  df
}

```

``` {r Import experiment list}

participant_assignment_all <- read_excel("Experiment Assignment.xlsx",sheet = "Participant ID")
participant_assignment_all <- participant_assignment_all[participant_assignment_all[, "Status"]=="Completed", ]
#participant_assignment <- participant_assignment_all[participant_assignment_all[, "participant_ID"]==filter_participant_ID, ]
participant_assignment_all$TrialScenario <- "00"
participant_assignment_all$TrialTask <- NA
participant_assignment_all$participant_ID <- transform(participant_assignment_all, participant_ID = as.character(participant_ID))$participant_ID
participant_assignment_all$`Alert Perception Order`[which(participant_assignment_all$`Alert Perception Order` == "None")] <- NA

exp_list <- participant_assignment_all |>
  pivot_longer(cols = c("TrialScenario","1st Scenario","2nd Scenario","3rd Scenario","4th Scenario"), names_to = "scenario_order", values_to = "scenario") |>
  select(participant_ID, scenario, group,Sim_freq, `Appointment Date`,scenario_order)

secondary_task_list <- participant_assignment_all |>
  pivot_longer(cols = c("TrialTask","Secondary task1","Secondary task2","Secondary task3","Secondary task4"), names_to = "secondary_task_order", values_to = "secondary_task") |>
  select(participant_ID,secondary_task_order, secondary_task)


exp_list$design <- sapply(str_split(tools::file_path_sans_ext(exp_list$scenario),"_"), `[`, 1)
exp_list$scenario <- sapply(str_split(tools::file_path_sans_ext(exp_list$scenario),"_"), `[`, 2)
exp_list$secondaryTask <- secondary_task_list$secondary_task
#exp_list$order <- substr(exp_list$scenario, 1,1)
#exp_list$scenario <- substr(exp_list$scenario, 2,2)
exp_list$group <- replace(exp_list$group, is.na(exp_list$scenario), "Trial")
exp_list$scenario <- replace(exp_list$scenario, is.na(exp_list$scenario), "00")


exp_list$scenario_no <- str_split_fixed(exp_list$scenario, "", 2)[,2]
exp_list$secondaryTask2 <- exp_list$secondaryTask
exp_list$secondaryTask2[which(exp_list$secondaryTask2 == "L")] <- "0"
exp_list$expGroup <- exp_list$group
exp_list$expGroup[which(exp_list$expGroup == "Single - Soft" | exp_list$expGroup == "Single - Strong")] <- "Single"
exp_list$Groups <- exp_list$group
exp_list$Groups[which(exp_list$Groups == "Single - Soft")] <- "Mild"
exp_list$Groups[which(exp_list$Groups == "Single - Strong")] <- "Strong"


alert_perception <- participant_assignment_all %>%
  select(participant_ID, group, `Alert Perception Order`)
alert_perception[c('1st Alert', '2nd Alert')] <- str_split_fixed(alert_perception$`Alert Perception Order`, '', 2)

scenario_list <- unique(exp_list[c("scenario_no", "Groups", "design", "secondaryTask2")])

```

``` {r Import Simulation file list}
sim_list <- data.frame(dir = list.dirs(path = "./SimData"))
# sim_list <- data.frame(dir = list.dirs(path = "./TempData"))
sim_list$participant_id_path <- lapply(str_split(sim_list$dir, "/"),head, n=3)
sim_list$folderSplit <- lapply(str_split(sim_list$dir, "_"),tail, n=4)
sim_list <- sim_list[which(sapply(sapply(sim_list[,"folderSplit",drop=F],"[",),length)>1),]
for (i in 1:length(sim_list$dir)){
  
  sim_list$participant_ID[i] <- sim_list$participant_id_path[[i]][3]
  
  sim_list$scenario[i] <-  substr(sim_list$folderSplit[[i]][2],1,2)
  
  if (sim_list$scenario[i] == "00"){ #Test drive
    sim_list$design[i] <- "00"
  }
  else {
    sim_list$design[i] <-  substr(sim_list$folderSplit[[i]][1],1,1)
  }
  
  
  sim_list$sim_folder_name[i] <- sim_list$dir[i]
  sim_list$sim_file_name[i] <- as.list(list.files(path = sim_list$sim_folder_name[i],pattern = "\\.csv$"))
  file_date <- sim_list$folderSplit[[i]][3]
  file_time <- sim_list$folderSplit[[i]][4]
  sim_list$test_start_date_time[i] <- as.POSIXct(paste(file_date,file_time), format = "%Y.%m.%d %H.%M.%OS",origin=as.POSIXct("1970-01-01", tz="EST"), tz="EST")
}

```

```{undefined eval=FALSE, include=FALSE}
HR_dir <- "./HRData"
HR_list <- data.frame(HRfile = list.files(path = HR_dir,pattern = "\\.zip$"))
HR_list$HR_startTime <- sapply(str_split(tools::file_path_sans_ext(HR_list$HRfile),"_"), `[`, 1)
HR_list$HR_startTime <- as.POSIXct(as.numeric(HR_list$HR_startTime), format = "%Y.%m.%d %H.%M.%OS",origin=as.POSIXct("1970-01-01", tz="GMT"), tz="EST")
HR_list$participant_ID <- as.numeric(sapply(str_split(tools::file_path_sans_ext(HR_list$HRfile),"_"), `[`, 2))
#HR_list <- HR_list[HR_list[, "participant_ID"]==filter_participant_ID, ]


exp_list <- cbind(exp_list[order(exp_list$"Appointment Date"),], HR_list[order(HR_list$"HR_startTime"),]["HRfile"])

```

```{r eyetracking cleaning}

eyetracking <- read_excel("Export/EyeTrackingExtract.xlsx",sheet = "EyeTrackingStats")
eyetracking_Phone2 <- read_excel("Export/EyeTrackingExtract.xlsx",sheet = "EyeTrackingStats_phone2")

mergeColumns <- function(array1, array2){ 
  mergedArray <- pmax(ifelse(is.na(array1), 0, array1), ifelse(is.na(array2), 0, array2))
  mergedArray[mergedArray == 0] <- NA
  return(mergedArray)
}

#PreAlert
eyetracking$PreAlert_Phone_Number_of_Glances <- mergeColumns(eyetracking$PreAlert_Phone_Number_of_Glances,eyetracking_Phone2$PreAlert_Phone_Number_of_Glances)
eyetracking$`PreAlert_Phone_Nr._of_glances_>_2s` <- mergeColumns(eyetracking$`PreAlert_Phone_Nr._of_glances_>_2s`,eyetracking_Phone2$`PreAlert_Phone_Nr._of_glances_>_2s`)
eyetracking$`PreAlert_Phone_Total_Glance_time_[s]` <- mergeColumns(eyetracking$`PreAlert_Phone_Total_Glance_time_[s]`,eyetracking_Phone2$`PreAlert_Phone_Total_Glance_time_[s]`)
eyetracking$`PreAlert_Phone_Mean_Glance_Duration_[s]` <- mergeColumns(eyetracking$`PreAlert_Phone_Mean_Glance_Duration_[s]`,eyetracking_Phone2$`PreAlert_Phone_Mean_Glance_Duration_[s]`)
eyetracking$`PreAlert_Phone_AOI_Attention_Ratio_[%]` <- mergeColumns(eyetracking$`PreAlert_Phone_AOI_Attention_Ratio_[%]`,eyetracking_Phone2$`PreAlert_Phone_AOI_Attention_Ratio_[%]`)
eyetracking$`PreAlert_Phone_Maximum_Glance_Duration_[s]` <- mergeColumns(eyetracking$`PreAlert_Phone_Maximum_Glance_Duration_[s]`,eyetracking_Phone2$`PreAlert_Phone_Maximum_Glance_Duration_[s]`)
eyetracking$`PreAlert_Phone_Minimum_Glance_Duration_[s]` <- mergeColumns(eyetracking$`PreAlert_Phone_Minimum_Glance_Duration_[s]`,eyetracking_Phone2$`PreAlert_Phone_Minimum_Glance_Duration_[s]`)
# eyetracking$`PreAlert_Phone_Time_to_first_glance_[s]` <- mergeColumns(eyetracking$`PreAlert_Phone_Time_to_first_glance_[s]`,eyetracking_Phone2$`PreAlert_Phone_Time_to_first_glance_[s]`)
# eyetracking$`PreAlert_Phone2_Glance_Rate_[1/s]` <- mergeColumns(eyetracking$`PreAlert_Phone2_Glance_Rate_[1/s]`,eyetracking_Phone2$`PreAlert_Phone2_Glance_Rate_[1/s]`)
# eyetracking$`PreAlert_Phone2_Mean_fixation_duration_left_[ms]` <- mergeColumns(eyetracking$`PreAlert_Phone2_Mean_fixation_duration_left_[ms]`,eyetracking_Phone2$`PreAlert_Phone2_Mean_fixation_duration_left_[ms]`)
# eyetracking$`PreAlert_Phone2_Mean_fixation_duration_right_[ms]` <- mergeColumns(eyetracking$`PreAlert_Phone2_Mean_fixation_duration_right_[ms]`,eyetracking_Phone2$`PreAlert_Phone2_Mean_fixation_duration_right_[ms]`)
# eyetracking$PreAlert_Phone2_Number_of_fixations_left <- mergeColumns(eyetracking$PreAlert_Phone2_Number_of_fixations_left,eyetracking_Phone2$PreAlert_Phone2_Number_of_fixations_left)
# eyetracking$PreAlert_Phone2_Number_of_fixations_right <- mergeColumns(eyetracking$PreAlert_Phone2_Number_of_fixations_right,eyetracking_Phone2$PreAlert_Phone2_Number_of_fixations_right)


#TakeoverBeforeAlert
eyetracking$TakeoverBeforeAlert_Phone_Number_of_Glances <- mergeColumns(eyetracking$TakeoverBeforeAlert_Phone_Number_of_Glances,eyetracking_Phone2$TakeoverBeforeAlert_Phone_Number_of_Glances)
eyetracking$`TakeoverBeforeAlert_Phone_Nr._of_glances_>_2s` <- mergeColumns(eyetracking$`TakeoverBeforeAlert_Phone_Nr._of_glances_>_2s`,eyetracking_Phone2$`TakeoverBeforeAlert_Phone_Nr._of_glances_>_2s`)
eyetracking$`TakeoverBeforeAlert_Phone_Total_Glance_time_[s]` <- mergeColumns(eyetracking$`TakeoverBeforeAlert_Phone_Total_Glance_time_[s]`,eyetracking_Phone2$`TakeoverBeforeAlert_Phone_Total_Glance_time_[s]`)
eyetracking$`TakeoverBeforeAlert_Phone_Mean_Glance_Duration_[s]` <- mergeColumns(eyetracking$`TakeoverBeforeAlert_Phone_Mean_Glance_Duration_[s]`,eyetracking_Phone2$`TakeoverBeforeAlert_Phone_Mean_Glance_Duration_[s]`)
eyetracking$`TakeoverBeforeAlert_Phone_AOI_Attention_Ratio_[%]` <- mergeColumns(eyetracking$`TakeoverBeforeAlert_Phone_AOI_Attention_Ratio_[%]`,eyetracking_Phone2$`TakeoverBeforeAlert_Phone_AOI_Attention_Ratio_[%]`)
eyetracking$`TakeoverBeforeAlert_Phone_Maximum_Glance_Duration_[s]` <- mergeColumns(eyetracking$`TakeoverBeforeAlert_Phone_Maximum_Glance_Duration_[s]`,eyetracking_Phone2$`TakeoverBeforeAlert_Phone_Maximum_Glance_Duration_[s]`)
eyetracking$`TakeoverBeforeAlert_Phone_Minimum_Glance_Duration_[s]` <- mergeColumns(eyetracking$`TakeoverBeforeAlert_Phone_Minimum_Glance_Duration_[s]`,eyetracking_Phone2$`TakeoverBeforeAlert_Phone_Minimum_Glance_Duration_[s]`)
eyetracking$`TakeoverBeforeAlert_Phone_Time_to_first_glance_[s]` <- mergeColumns(eyetracking$`TakeoverBeforeAlert_Phone_Time_to_first_glance_[s]`,eyetracking_Phone2$`TakeoverBeforeAlert_Phone_Time_to_first_glance_[s]`)


#PostAlert
eyetracking$PostAlert_Phone_Number_of_Glances <- mergeColumns(eyetracking$PostAlert_Phone_Number_of_Glances,eyetracking_Phone2$PostAlert_Phone_Number_of_Glances)
eyetracking$`PostAlert_Phone_Nr._of_glances_>_2s` <- mergeColumns(eyetracking$`PostAlert_Phone_Nr._of_glances_>_2s`,eyetracking_Phone2$`PostAlert_Phone_Nr._of_glances_>_2s`)
eyetracking$`PostAlert_Phone_Total_Glance_time_[s]` <- mergeColumns(eyetracking$`PostAlert_Phone_Total_Glance_time_[s]`,eyetracking_Phone2$`PostAlert_Phone_Total_Glance_time_[s]`)
eyetracking$`PostAlert_Phone_Mean_Glance_Duration_[s]` <- mergeColumns(eyetracking$`PostAlert_Phone_Mean_Glance_Duration_[s]`,eyetracking_Phone2$`PostAlert_Phone_Mean_Glance_Duration_[s]`)
eyetracking$`PostAlert_Phone_AOI_Attention_Ratio_[%]` <- mergeColumns(eyetracking$`PostAlert_Phone_AOI_Attention_Ratio_[%]`,eyetracking_Phone2$`PostAlert_Phone_AOI_Attention_Ratio_[%]`)
eyetracking$`PostAlert_Phone_Maximum_Glance_Duration_[s]` <- mergeColumns(eyetracking$`PostAlert_Phone_Maximum_Glance_Duration_[s]`,eyetracking_Phone2$`PostAlert_Phone_Maximum_Glance_Duration_[s]`)
eyetracking$`PostAlert_Phone_Minimum_Glance_Duration_[s]` <- mergeColumns(eyetracking$`PostAlert_Phone_Minimum_Glance_Duration_[s]`,eyetracking_Phone2$`PostAlert_Phone_Minimum_Glance_Duration_[s]`)
eyetracking$`PostAlert_Phone_Time_to_first_glance_[s]` <- mergeColumns(eyetracking$`PostAlert_Phone_Time_to_first_glance_[s]`,eyetracking_Phone2$`PostAlert_Phone_Time_to_first_glance_[s]`)


#Takeover
eyetracking$Takeover_Phone_Number_of_Glances <- mergeColumns(eyetracking$Takeover_Phone_Number_of_Glances,eyetracking_Phone2$Takeover_Phone_Number_of_Glances)
eyetracking$`Takeover_Phone_Nr._of_glances_>_2s` <- mergeColumns(eyetracking$`Takeover_Phone_Nr._of_glances_>_2s`,eyetracking_Phone2$`Takeover_Phone_Nr._of_glances_>_2s`)
eyetracking$`Takeover_Phone_Total_Glance_time_[s]` <- mergeColumns(eyetracking$`Takeover_Phone_Total_Glance_time_[s]`,eyetracking_Phone2$`Takeover_Phone_Total_Glance_time_[s]`)
eyetracking$`Takeover_Phone_Mean_Glance_Duration_[s]` <- mergeColumns(eyetracking$`Takeover_Phone_Mean_Glance_Duration_[s]`,eyetracking_Phone2$`Takeover_Phone_Mean_Glance_Duration_[s]`)
eyetracking$`Takeover_Phone_AOI_Attention_Ratio_[%]` <- mergeColumns(eyetracking$`Takeover_Phone_AOI_Attention_Ratio_[%]`,eyetracking_Phone2$`Takeover_Phone_AOI_Attention_Ratio_[%]`)
eyetracking$`Takeover_Phone_Maximum_Glance_Duration_[s]` <- mergeColumns(eyetracking$`Takeover_Phone_Maximum_Glance_Duration_[s]`,eyetracking_Phone2$`Takeover_Phone_Maximum_Glance_Duration_[s]`)
eyetracking$`Takeover_Phone_Minimum_Glance_Duration_[s]` <- mergeColumns(eyetracking$`Takeover_Phone_Minimum_Glance_Duration_[s]`,eyetracking_Phone2$`Takeover_Phone_Minimum_Glance_Duration_[s]`)
eyetracking$`Takeover_Phone_Time_to_first_glance_[s]` <- mergeColumns(eyetracking$`Takeover_Phone_Time_to_first_glance_[s]`,eyetracking_Phone2$`Takeover_Phone_Time_to_first_glance_[s]`)

  
#PostTakeover
eyetracking$PostTakeover_Phone_Number_of_Glances <- mergeColumns(eyetracking$PostTakeover_Phone_Number_of_Glances,eyetracking_Phone2$PostTakeover_Phone_Number_of_Glances)
eyetracking$`PostTakeover_Phone_Nr._of_glances_>_2s` <- mergeColumns(eyetracking$`PostTakeover_Phone_Nr._of_glances_>_2s`,eyetracking_Phone2$`PostTakeover_Phone_Nr._of_glances_>_2s`)
eyetracking$`PostTakeover_Phone_Total_Glance_time_[s]` <- mergeColumns(eyetracking$`PostTakeover_Phone_Total_Glance_time_[s]`,eyetracking_Phone2$`PostTakeover_Phone_Total_Glance_time_[s]`)
eyetracking$`PostTakeover_Phone_Mean_Glance_Duration_[s]` <- mergeColumns(eyetracking$`PostTakeover_Phone_Mean_Glance_Duration_[s]`,eyetracking_Phone2$`PostTakeover_Phone_Mean_Glance_Duration_[s]`)
eyetracking$`PostTakeover_Phone_AOI_Attention_Ratio_[%]` <- mergeColumns(eyetracking$`PostTakeover_Phone_AOI_Attention_Ratio_[%]`,eyetracking_Phone2$`PostTakeover_Phone_AOI_Attention_Ratio_[%]`)
eyetracking$`PostTakeover_Phone_Maximum_Glance_Duration_[s]` <- mergeColumns(eyetracking$`PostTakeover_Phone_Maximum_Glance_Duration_[s]`,eyetracking_Phone2$`PostTakeover_Phone_Maximum_Glance_Duration_[s]`)
eyetracking$`PostTakeover_Phone_Minimum_Glance_Duration_[s]` <- mergeColumns(eyetracking$`PostTakeover_Phone_Minimum_Glance_Duration_[s]`,eyetracking_Phone2$`PostTakeover_Phone_Minimum_Glance_Duration_[s]`)
eyetracking$`PostTakeover_Phone_Time_to_first_glance_[s]` <- mergeColumns(eyetracking$`PostTakeover_Phone_Time_to_first_glance_[s]`,eyetracking_Phone2$`PostTakeover_Phone_Time_to_first_glance_[s]`)

  
```

``` {r Merging file lists}

exp_list <- join(exp_list, sim_list, type = "inner", by = c("participant_ID","scenario","design"))


```


``` {r Extracting Simulation Data}
#Extracting data
exp_data <- data.frame()
baseline_data <- data.frame()
takeover_data_all <- data.frame()
driver_reactions <- data.frame()
driving_performance <- data.frame()
no_alert_exp <- data.frame()

triggerSteps <- exp_list %>%
  select(participant_ID,design,scenario,scenario_order,test_start_date_time)
triggerSteps$triggerID <- NA
triggerSteps$triggerBeginSTEP <- NA
triggerSteps$triggerBeginDatetime <- NA
triggerSteps$triggerLastSTEP <- NA
triggerSteps$triggerLastDatetime <- NA

for (i in 1:length(exp_list[[1]])) {
  
  downsample_factor <- exp_list$Sim_freq[i] / target_sampling_rate
  
  current_exp <- data.frame(participant_ID = exp_list$participant_ID[i],
                       group = exp_list$group[i],
                       design = exp_list$design[i],
                       scenario = exp_list$scenario[i])

  if (current_exp$scenario == "00") {
    if (extractBaselineData){
      # Down Sample Sim Data
    tempData <- read.csv(paste0(exp_list$sim_folder_name[i],"/",exp_list$sim_file_name[i]),header=TRUE, sep=";", dec=".", stringsAsFactors=FALSE)
    tempData <- tempData[seq(1, nrow(tempData), by = downsample_factor), ]
    baseline_data <- rbind.fill(baseline_data,tempData)
    next
  }
  else {next}
  }  
  
  tempData <- read.csv(paste0(exp_list$sim_folder_name[i],"/",exp_list$sim_file_name[i]),header=TRUE, sep=";", dec=".", stringsAsFactors=FALSE)
  
  tempData$date_time <- exp_list$test_start_date_time[i]+(tempData$STEP/exp_list$Sim_freq)
  
  tempData$design <- exp_list$design[i]
  tempData$group <- exp_list$group[i]
  tempData$scenario <- exp_list$scenario[i]
  tempData$participant_ID = exp_list$participant_ID[i]
  
  if (length(which(tempData$Driver_Performance.inputs.trigger_ID > 1)) == 0) {
       # Down Sample Sim Data
    tempData <- tempData[seq(1, nrow(tempData), by = downsample_factor), ]
    #exp_data <- rbind.fill(exp_data,tempData)
    
    # Log experiments with no alert
    no_alert_exp <- rbind.fill(no_alert_exp,current_exp)
    message("\n No trigger issued for ", current_exp$participant_ID," in ", paste0(current_exp$design, "_", current_exp$scenario), "\n")
    next
  }
  
    # Find trigger begin and last steps
    rle_trigger <- rle(tempData[which(tempData$Driver_Performance.inputs.trigger_ID > 1),]$Driver_Performance.inputs.trigger_ID)
    endStep = cumsum(rle_trigger$lengths)
    startStep = c(1, lag(endStep)[-1] + 1)
  
  
    beginSteps <- aggregate(cbind(STEP,date_time) ~ + Driver_Performance.inputs.trigger_ID, data = tempData[which(tempData$Driver_Performance.inputs.trigger_ID > 1),], FUN = min)
    names(beginSteps)[length(beginSteps)-1] <- "triggerBeginSTEP"
    names(beginSteps)[length(beginSteps)] <- "triggerBeginDatetime"
    lastSteps <- aggregate(cbind(STEP,date_time) ~ + Driver_Performance.inputs.trigger_ID, data = tempData[which(tempData$Driver_Performance.inputs.trigger_ID > 1),], FUN = max)
    names(lastSteps)[length(lastSteps)-1] <- "triggerLastSTEP"
    names(beginSteps)[length(beginSteps)] <- "triggerLastDatetime"

    tempTriggerSteps <- inner_join(beginSteps, lastSteps, by = c("Driver_Performance.inputs.trigger_ID"))
    rm(beginSteps,lastSteps)
    
    #Filter only main trigger
    tempTriggerSteps <- tempTriggerSteps[which(tempTriggerSteps$Driver_Performance.inputs.trigger_ID == trigger_ID_config[which(trigger_ID_config$design == current_exp$design),]$trigger_ID),]
    
    triggerSteps$triggerID[which(triggerSteps$participant_ID == exp_list$participant_ID[i] & triggerSteps$scenario==exp_list$scenario[i])] <- tempTriggerSteps$Driver_Performance.inputs.trigger_ID
    triggerSteps$triggerBeginSTEP[which(triggerSteps$participant_ID == exp_list$participant_ID[i] & triggerSteps$scenario==exp_list$scenario[i])] <- tempTriggerSteps$triggerBeginSTEP
    triggerSteps$triggerLastSTEP[which(triggerSteps$participant_ID == exp_list$participant_ID[i] & triggerSteps$scenario==exp_list$scenario[i])] <- tempTriggerSteps$triggerLastSTEP  
    #add margin to evaluate data after trigger
    pre_takeover_margin_step <- pre_takeover_sec*1000
    after_trigger_margin_step <- post_takeover_sec*1000
  
    #reassign trigger_ID to pre and after takeover 
    tempData$Driver_Performance.inputs.trigger_ID[tempData$STEP>= tempTriggerSteps$triggerBeginSTEP-pre_takeover_margin_step & tempData$STEP <= tempTriggerSteps$triggerBeginSTEP+after_trigger_margin_step] <- tempTriggerSteps$Driver_Performance.inputs.trigger_ID
    
    #Driver Reaction Extraction
    
    takeover_response <- tempData[tempData$Driver_Performance.inputs.trigger_ID == tempTriggerSteps$Driver_Performance.inputs.trigger_ID,]#%>%
      # select(STEP, design,group,scenario,date_time, Driver_Performance.inputs.trigger_ID,ends_with("reaction_time"), ends_with("reaction_detected"))
      # select(STEP, design,group,scenario,date_time, starts_with("Driver_Performance."), contains("velocit"),contains("acceleration"))
    
    takeover_response <- replaceColNamePattern(takeover_response,"Driver_Performance.inputs.","")
    takeover_response <- replaceColNamePattern(takeover_response,"Driver_Performance.outputs.","")
    
    reaction_types <- c("brake","steering","indicator")
    
    temp_driver_reactions <- data.frame()
    for (j in 1:length(reaction_types)) {
      reaction_type <- reaction_types[j]
      detected_response <- takeover_response[takeover_response[paste0(reaction_type,".reaction_detected")]==1,]
      
      if (length(detected_response>0)){
        
        detected_response <- detected_response %>%
          distinct(trigger_ID,scenario, .keep_all=TRUE)
        detected_response$reaction_type <- reaction_type
        detected_response$reaction_time <- detected_response[[paste0(reaction_type,".reaction_time")]]
        temp_driver_reactions <- rbind.fill(temp_driver_reactions,detected_response)
    
      }
      
      rm(detected_response)
    }

    # Crash analysis
    temp_driving_performance <- current_exp
        #braking
    if (length(temp_driver_reactions[which(temp_driver_reactions$reaction_type == "brake"),]>0)){

    MaxBrakeAccel <- aggregate(brake.Longitudinal_Accelerations ~ + participant_ID + design + scenario + trigger_ID, data = takeover_response[which(takeover_response$brake.reaction_detected==1),], FUN = min) #min because braking acceleration is negative
    names(MaxBrakeAccel)[length(MaxBrakeAccel)] <- "Max_Brake_Acceleration"
    
    temp_driving_performance$Max_Brake_Acceleration <- MaxBrakeAccel$Max_Brake_Acceleration
    }
    #steering
    if (length(temp_driver_reactions[which(temp_driver_reactions$reaction_type == "steering"),]>0)){
          MaxSteerAccelNeg <- aggregate(steering.Lateral_Accelerations ~ + participant_ID + design + group + scenario + trigger_ID, data = takeover_response[which(takeover_response$steering.reaction_detected==1),], FUN = min) #min for acceleration that is negative
    names(MaxSteerAccelNeg)[length(MaxSteerAccelNeg)] <- "Max_lateral_Acceleration_Neg"
    MaxSteerAccelPos <- aggregate(steering.Lateral_Accelerations ~ + participant_ID + design + group + scenario + trigger_ID, data = takeover_response[which(takeover_response$steering.reaction_detected==1),], FUN = max)
    names(MaxSteerAccelPos)[length(MaxSteerAccelPos)] <- "Max_lateral_Acceleration_Pos"
    MaxSteerAccel <- left_join(MaxSteerAccelNeg, MaxSteerAccelPos, by = c("group","scenario","trigger_ID"))
    rm(MaxSteerAccelPos,MaxSteerAccelNeg)
    temp_driving_performance$Max_lateral_Acceleration_Neg <- MaxSteerAccel$Max_lateral_Acceleration_Neg
    temp_driving_performance$Max_lateral_Acceleration_Pos <- MaxSteerAccel$Max_lateral_Acceleration_Pos
    }
    
    # ACC
    temp_driving_performance$Min_front_Distance <- min(takeover_response$ADAS.Outputs.ACC.ACC_Actual_Distance)
    
    # AP
    temp_driving_performance$Error_from_LaneCenter <- min(takeover_response$ADAS.Outputs.AP.AP_Error_fromcenter)
    #temp_driving_performance$AP_Off_Step <- min(takeover_response[which(takeover_response$ADAS.Outputs.AP.AP_On == 0),]$STEP)+1
    temp_driving_performance$Takeover_Before_Alert <- takeover_response[which(takeover_response$STEP == tempTriggerSteps$triggerBeginSTEP+1),]$ADAS.Outputs.AP.AP_On == 0
    

    #AEB
    temp_driving_performance$AEBMinDistance <- min(takeover_response$ADAS.Outputs.AEB.Minimum_distance)

    temp_driving_performance$AEBMinTimeThreshold <- min(takeover_response$ADAS.Outputs.AEB.AEB_TimeToCollision_Threshold)

    
    #collisions
    Collisions = takeover_response[which(takeover_response$WorldSim.ego.Sensors.Collision.Status==1),]
    if (length(Collisions$STEP)>0){
      Collisions$gap <- c(NA, with(Collisions, STEP[-1] - STEP[-nrow(Collisions)]))
      Collisions <- Collisions[which(Collisions$gap>500),]
    }
    temp_driving_performance$collisions <- length(Collisions[,1])
    
    driving_performance <- rbind.fill(driving_performance, temp_driving_performance)

    if (length(temp_driver_reactions) > 0) {
    temp_driver_reactions <- temp_driver_reactions %>%
      select(STEP,participant_ID, group, design,scenario,date_time, trigger_ID, contains("reaction"))
    
    driver_reactions <- rbind.fill(driver_reactions,temp_driver_reactions)
    } else {
      message("\n No driver reaction from ", current_exp$participant_ID," in ", paste0(current_exp$design, "_", current_exp$scenario), "\n")

    }
    
    # Down Sample Simumulation Data
  tempData <- tempData %>%
    select(STEP,date_time,participant_ID,design,scenario, starts_with("Driver_Performance."),contains("ADAS"), contains("driver_demands"), contains("Cockpit"), contains("velocit"),contains("acceleration"))
  tempData <- tempData[seq(1, nrow(tempData), by = downsample_factor), ]
  exp_data <- rbind.fill(exp_data,tempData)

}
rm(tempData)


```

```{r Analysis Prep}
AP_Off_steps <- aggregate(STEP~+participant_ID+scenario+group+design, data = takeover_data_all[which(takeover_data_all$ADAS.Outputs.AP.AP_On == 0),], FUN = "min")
names(AP_Off_steps)[names(AP_Off_steps) == "STEP"] <- "AP_Off_Step"

takeover_data_all <- left_join(takeover_data_all,AP_Off_steps)
driving_performance <- left_join(driving_performance,AP_Off_steps,by = c("participant_ID","group","scenario","design"),multiple = "first")


driver_react_agg <- left_join(driver_reactions,exp_list, by = c("participant_ID","group","scenario","design"))

driver_react_agg_min <- aggregate(cbind(reaction_type,reaction_time) ~ + participant_ID + scenario_no + secondaryTask2 + expGroup + Groups + design, data = driver_react_agg, FUN = min)
driver_react_agg_min$reaction_time <- transform(driver_react_agg_min, reaction_time = as.numeric(reaction_time))$reaction_time

driver_react_agg_avg_brk <- aggregate(reaction_time ~ + participant_ID + scenario_no + secondaryTask2 + expGroup + Groups + design, data = driver_react_agg[which(driver_react_agg$reaction_type == 'brake'),], FUN = mean)
driver_react_agg_avg_brk$reaction_type <- 'brake'

driver_react_agg_avg_str <- aggregate(reaction_time ~ + participant_ID + scenario_no + secondaryTask2 + expGroup + Groups + design, data = driver_react_agg[which(driver_react_agg$reaction_type == 'steering'),], FUN = mean)
driver_react_agg_avg_str$reaction_type <- 'steering'

driver_react_agg_avg_ind <- aggregate(reaction_time ~ + participant_ID + scenario_no + secondaryTask2 + expGroup + Groups + design, data = driver_react_agg[which(driver_react_agg$reaction_type == 'indicator'),], FUN = mean)
driver_react_agg_avg_ind$reaction_type <- 'indicator'

driver_react_agg_avg <- rbind(driver_react_agg_avg_brk,driver_react_agg_avg_str,driver_react_agg_avg_ind)
rm(driver_react_agg_avg_brk,driver_react_agg_avg_str,driver_react_agg_avg_ind)


react_agg_min_avg <- aggregate(reaction_time ~ + scenario_no + Groups + design + secondaryTask2, data = driver_react_agg_min, FUN = mean)
names(react_agg_min_avg)[names(react_agg_min_avg) == "reaction_time"] <- "reaction_time_min_avg"

driver_react_agg_min <- left_join(driver_react_agg_min,react_agg_min_avg, by = c("scenario_no", "Groups", "design", "secondaryTask2"))
driver_react_agg_min$reaction_time_diff <- driver_react_agg_min$reaction_time - driver_react_agg_min$reaction_time_min_avg

react_rmse_byScenario <- aggregate(reaction_time_diff ~ + scenario_no + secondaryTask2, data = driver_react_agg_min, FUN =function(x) sqrt(mean(x^2)))
names(react_rmse_byScenario)[names(react_rmse_byScenario) == "reaction_time_diff"] <- "reaction_time_rmse"

react_rmse_byScenario
```

```{r Export Data}
write_csv(takeover_data_all, "Export/takeover_data.csv", na = "")
write_csv(driver_reactions, "Export/driver_reactions.csv", na = "")
write_csv(triggerSteps, "Export/scenario_triggers.csv", na = "")
write_csv(driving_performance, "Export/driving_performance.csv", na = "")
write_csv(exp_data, "Export/exp_data_downsampled.csv", na = "")
write_csv(exp_list, "Export/exp_list.csv", na = "")
write_csv(driver_react_agg_min, "Export/driver_reactions_min.csv", na = "")
write_csv(driver_react_agg_avg, "Export/driver_reactions_avg.csv", na = "")
write_csv(alert_perception, "Export/alert_perception.csv", na = "")
write_csv(eyetracking, "Export/eyetracking.csv", na = "")

```


```{r Data Analysis}

#ANOVA
cat("Scenario 1","No Secondary Task","\n")
react1.0.aov <- aov(reaction_time ~ Groups, data = driver_react_agg_min[which(driver_react_agg_min$scenario_no == 1& driver_react_agg_min$secondaryTask2 == "0"),])
summary(react1.0.aov)
TukeyHSD(react1.0.aov)
cat("Scenario 1","Typing","\n")
react1.H.aov <- aov(reaction_time ~ Groups, data = driver_react_agg_min[which(driver_react_agg_min$scenario_no == 1& driver_react_agg_min$secondaryTask2 == "H"),])
summary(react1.H.aov)
TukeyHSD(react1.H.aov)

cat("Scenario 2","No Secondary Task","\n")
react2.0.aov <- aov(reaction_time ~ Groups, data = driver_react_agg_min[which(driver_react_agg_min$scenario_no == 2& driver_react_agg_min$secondaryTask2 == "0"),])
summary(react2.0.aov)
TukeyHSD(react2.0.aov)
cat("Scenario 2","Typing","\n")
react2.H.aov <- aov(reaction_time ~ Groups, data = driver_react_agg_min[which(driver_react_agg_min$scenario_no == 2& driver_react_agg_min$secondaryTask2 == "H"),])
summary(react2.H.aov)
TukeyHSD(react2.H.aov)

cat("Scenario 3","No Secondary Task","\n")
react3.0.aov <- aov(reaction_time ~ Groups, data = driver_react_agg_min[which(driver_react_agg_min$scenario_no == 3& driver_react_agg_min$secondaryTask2 == "0"),])
summary(react3.0.aov)
TukeyHSD(react3.0.aov)
cat("Scenario 3","Typing","\n")
react3.H.aov <- aov(reaction_time ~ Groups, data = driver_react_agg_min[which(driver_react_agg_min$scenario_no == 3& driver_react_agg_min$secondaryTask2 == "H"),])
summary(react3.H.aov)
TukeyHSD(react3.H.aov)

cat("Scenario 4","No Secondary Task","\n")
react4.0.aov <- aov(reaction_time ~ Groups, data = driver_react_agg_min[which(driver_react_agg_min$scenario_no == 4& driver_react_agg_min$secondaryTask2 == "0"),])
summary(react4.0.aov)
TukeyHSD(react4.0.aov)
cat("Scenario 4","Typing","\n")
react4.H.aov <- aov(reaction_time ~ Groups, data = driver_react_agg_min[which(driver_react_agg_min$scenario_no == 4& driver_react_agg_min$secondaryTask2 == "H"),])
summary(react4.H.aov)
TukeyHSD(react4.H.aov)



# 
# anova_brake <- lmer(cbind(reaction_time,reaction_type) ~ (1|secondaryTask2) * (1|design) + (1|expGroup), data = driver_react_agg_min[which(driver_react_agg_min$scenario_no == 2),])
# summary(anova_brake)
# # [which(driver_react_agg_min$scenario_no == 3 & driver_react_agg_min$secondaryTask2 == "0" & driver_react_agg_min$group != "Single - Strong" & driver_react_agg_min$reaction_type == "brake"),]
# #T-Test
# t_test_reaction_noTask_1 <- t.test(reaction_time ~ group, data = driver_react_agg_min[which(driver_react_agg_min$scenario_no == 1 & driver_react_agg_min$secondaryTask2 == "0" & driver_react_agg_min$group != "Single - Strong"),], paired = FALSE, var.equal = FALSE)
# t_test_reaction_noTask_2 <- t.test(reaction_time ~ group, data = driver_react_agg_min[which(driver_react_agg_min$scenario_no == 2 & driver_react_agg_min$secondaryTask2 == "0" & driver_react_agg_min$group != "Single - Strong"),], paired = FALSE, var.equal = FALSE)
# t_test_reaction_noTask_3 <- t.test(reaction_time ~ group, data = driver_react_agg_min[which(driver_react_agg_min$scenario_no == 3 & driver_react_agg_min$secondaryTask2 == "0" & driver_react_agg_min$group != "Single - Strong"),], paired = FALSE, var.equal = FALSE)
# t_test_reaction_noTask_4 <- t.test(reaction_time ~ group, data = driver_react_agg_min[which(driver_react_agg_min$scenario_no == 4 & driver_react_agg_min$secondaryTask2 == "0" & driver_react_agg_min$group != "Single - Strong"),], paired = FALSE, var.equal = FALSE)
# 
# t_test_reaction_typing_1 <- t.test(reaction_time ~ group, data = driver_react_agg_min[which(driver_react_agg_min$scenario_no == 1 & driver_react_agg_min$secondaryTask2 == "H" & driver_react_agg_min$group != "Single - Soft"),], paired = FALSE, var.equal = FALSE)
# t_test_reaction_typing_2 <- t.test(reaction_time ~ group, data = driver_react_agg_min[which(driver_react_agg_min$scenario_no == 2 & driver_react_agg_min$secondaryTask2 == "H" & driver_react_agg_min$group != "Single - Soft"),], paired = FALSE, var.equal = FALSE)
# t_test_reaction_typing_3 <- t.test(reaction_time ~ group, data = driver_react_agg_min[which(driver_react_agg_min$scenario_no == 3 & driver_react_agg_min$secondaryTask2 == "H" & driver_react_agg_min$group != "Single - Soft"),], paired = FALSE, var.equal = FALSE)
# t_test_reaction_typing_4 <- t.test(reaction_time ~ group, data = driver_react_agg_min[which(driver_react_agg_min$scenario_no == 4 & driver_react_agg_min$secondaryTask2 == "H" & driver_react_agg_min$group != "Single - Soft"),], paired = FALSE, var.equal = FALSE)

```

```{r Similarity}
library(vegan)

jaccard <- function(x, y) {
    intersection = length(intersect(x, y))
    union = length(x) + length(y) - intersection
    return (intersection/union)
}

cat("Scenario 1","No Secondary Task","\n")
single_data1 <- driver_react_agg_min[which(driver_react_agg_min$scenario_no == 1& driver_react_agg_min$secondaryTask2 == "0"& driver_react_agg_min$Groups == "Mild"),]$reaction_time
dynamic_data1 <- driver_react_agg_min[which(driver_react_agg_min$scenario_no == 1& driver_react_agg_min$secondaryTask2 == "0" &driver_react_agg_min$Groups == "Dynamic"),]$reaction_time
print(jaccard(x = single_data1, y = dynamic_data1))
vegdist(c(single_data1,dynamic_data1), method = "jaccard")

cat("Scenario 1","Typing","\n")
single_data1 <- driver_react_agg_min[which(driver_react_agg_min$scenario_no == 1& driver_react_agg_min$secondaryTask2 == "H"& driver_react_agg_min$Groups == "Strong"),]$reaction_time
dynamic_data1 <- driver_react_agg_min[which(driver_react_agg_min$scenario_no == 1& driver_react_agg_min$secondaryTask2 == "H" &driver_react_agg_min$Groups == "Dynamic"),]$reaction_time
print(jaccard(x = single_data1, y = dynamic_data1))
vegdist(c(single_data1,dynamic_data1), method = "jaccard")



cat("Scenario 2","No Secondary Task","\n")
single_data2 <- driver_react_agg_min[which(driver_react_agg_min$scenario_no == 2& driver_react_agg_min$secondaryTask2 == "0"& driver_react_agg_min$Groups == "Mild"),]$reaction_time
dynamic_data2 <- driver_react_agg_min[which(driver_react_agg_min$scenario_no == 2& driver_react_agg_min$secondaryTask2 == "0" &driver_react_agg_min$Groups == "Dynamic"),]$reaction_time
print(jaccard(x = single_data2, y = dynamic_data2))

cat("Scenario 2","Typing","\n")
single_data2 <- driver_react_agg_min[which(driver_react_agg_min$scenario_no == 2& driver_react_agg_min$secondaryTask2 == "H"& driver_react_agg_min$Groups == "Strong"),]$reaction_time
dynamic_data2 <- driver_react_agg_min[which(driver_react_agg_min$scenario_no == 2& driver_react_agg_min$secondaryTask2 == "H" &driver_react_agg_min$Groups == "Dynamic"),]$reaction_time
print(jaccard(x = single_data2, y = dynamic_data2))



cat("Scenario 3","No Secondary Task","\n")
single_data3 <- driver_react_agg_min[which(driver_react_agg_min$scenario_no == 3& driver_react_agg_min$secondaryTask2 == "0"& driver_react_agg_min$Groups == "Mild"),]$reaction_time
dynamic_data3 <- driver_react_agg_min[which(driver_react_agg_min$scenario_no == 3& driver_react_agg_min$secondaryTask2 == "0" &driver_react_agg_min$Groups == "Dynamic"),]$reaction_time
print(jaccard(x = single_data3, y = dynamic_data3))

cat("Scenario 3","Typing","\n")
single_data3 <- driver_react_agg_min[which(driver_react_agg_min$scenario_no == 3& driver_react_agg_min$secondaryTask2 == "H"& driver_react_agg_min$Groups == "Strong"),]$reaction_time
dynamic_data3 <- driver_react_agg_min[which(driver_react_agg_min$scenario_no == 3& driver_react_agg_min$secondaryTask2 == "H" &driver_react_agg_min$Groups == "Dynamic"),]$reaction_time
print(jaccard(x = single_data3, y = dynamic_data3))


cat("Scenario 4","No Secondary Task","\n")
single_data4 <- driver_react_agg_min[which(driver_react_agg_min$scenario_no == 4& driver_react_agg_min$secondaryTask2 == "0"& driver_react_agg_min$Groups == "Mild"),]$reaction_time
dynamic_data4 <- driver_react_agg_min[which(driver_react_agg_min$scenario_no == 4& driver_react_agg_min$secondaryTask2 == "0" &driver_react_agg_min$Groups == "Dynamic"),]$reaction_time
print(jaccard(x = single_data4, y = dynamic_data4))

cat("Scenario 4","Typing","\n")
single_data4 <- driver_react_agg_min[which(driver_react_agg_min$scenario_no == 4& driver_react_agg_min$secondaryTask2 == "H"& driver_react_agg_min$Groups == "Strong"),]$reaction_time
dynamic_data4 <- driver_react_agg_min[which(driver_react_agg_min$scenario_no == 4& driver_react_agg_min$secondaryTask2 == "H" &driver_react_agg_min$Groups == "Dynamic"),]$reaction_time
print(jaccard(x = single_data4, y = dynamic_data4))

```